name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install and configure dependencies
      run: |
        checkout
        npm install --progress=false
        npm run-script build
        gh-pages --dist build
