name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install and configure dependencies
      run: |
        npm install --progress=false
        npm run-script build
        git config --global user.email "chandrasekhartiwari@gmail.com"
        git config --global user.name "CrazyDev-il"
        git remote set-url origin https://CrazyDev-il:66e164dd7b6bcb1b05fc7f58b4290194ad1efa23@github.com/CrazyDev-il/me.git
        npm run deploy
